//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakip15.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personell
    {
        public int PersonellId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> İzinGunu { get; set; }
        public Nullable<int> Departman { get; set; }
    }
}
